version: '3'

services:
  # NGSI-LD testing
  analytics-server:
    image: testserver
    ports:
     - "8080:8080"
  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "yang-push"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  # Edge Data Fabric
  edge-postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  edge-scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: edge-postgres
    ports:
      - "9098:9090"
    depends_on:
      - edge-postgres
  gnmic:
    image: ghcr.io/openconfig/gnmic:latest
    volumes:
      - ./gnmic/gnmic.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"

  #rml-streamer-gnmi: # See https://github.com/RMLio/RMLStreamer/#quick-start-docker---the-fast-way-to-test
  #  image: rmlio/rmlstreamer
  #  command: ["toFile, "-m", "mapping.ttl", "-o", "data"]
  #  volumes:
  #    - - myapp:/home/node/app
  #  input topic: gnmi
  #  output topic: rdf-gnmi
  #rdf-to-ngsi-ld-gnmi:
  #  input topic: rdf-yang-push
  ncclient:
    image: ncclient-collector
    command: "clab-telemetry-testbed-srl-xe-r2 GigabitEthernet1 1000"
    depends_on:
      - kafka
  #  output topic: rdf-gnmi
  #rml-streamer-yang-push: # See https://github.com/RMLio/RMLStreamer/#quick-start-docker---the-fast-way-to-test
  #  image: rmlio/rmlstreamer
  #  command: ["toFile, "-m", "mapping.ttl", "-o", "data"]
  #  volumes:
  #    - - myapp:/home/node/app
  #  input topic: yang-push
  #  output topic: rdf-yang-push
  #rdf-to-ngsi-ld-yang-push:
  #  input topic: rdf-yang-push
  # Cloud Data Fabric
  cloud-postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  cloud-scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: cloud-postgres
    ports:
      - "9099:9090"
    depends_on:
      - cloud-postgres
  morph-kgc:
    image: morph-kgc
    volumes:
      - ./containerlab/clab-telemetry-testbed-srl-xe/topology-data.json:/files/topology-data.json
      - ./mappings/containerlab/:/files
    command: "/files/config.ini"
    depends_on:
      - kafka
  rdf-to-ngsi-ld:
    image: rdf-to-ngsi-ld
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: containerlab
      BROKER_URI: http://cloud-scorpio:9090/ngsi-ld/v1
      DEBUG: True
    depends_on:
      - morph-kgc
      - kafka
networks:
  default:
    name: clab
    external: true
