version: '3'

services:
  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "rdf-streams"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgres
    ports:
      - "9099:9090"
    depends_on:
      - postgres
  rdf-to-ngsi-ld:
    image: rdf-to-ngsi-ld
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: rdf-streams
      BROKER_URI: http://scorpio:9090/ngsi-ld/v1
      DEBUG: False
    volumes:
      - ./results:/tmp
    depends_on:
      - kafka
      - scorpio
  rdf-generator:
    image: rdf-generator
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: rdf-streams
    depends_on:
      - kafka
      - scorpio
